const listData = {
    1: 'Demarcation of Site',
    2: 'STANDARED PROTECTOR COMPACTION TEST & FDT TEST',
    3: 'Layout of Foundation',
    4: 'Foundation Basement & Columns & Waterproofing Plot',
    5: 'Retaining Walls/ Stair Case',
    6: 'Water Proofing',
    7: 'Basement Lintels',
    8: 'Basement Slabs and Beams',
    9: 'Layout of Foundation Ground Floorwith Set Back',
    10: 'Construction Of Boundary Wall Upto D.P.C',
    11: 'Foundation Ground Floor Columns and stair case',
    12: 'Plint Beams',
    13: 'D.P.C level with set back Porch Level',
    14: 'Under Ground Water Tank',
    15: 'Foundation Ground Floor Lintels Beams (Door & Window)',
    16: 'Car Porch Slab and Beams',
    17: 'Fround Floor Slab & Beams, Projection & Stair Case',
    18: 'Layout of First Floor',
    19: 'First Floor Lintels Beams (Doors and Windows)	',
    20: 'First Floor Slab, Beams, Projection & Stairs',
    21: 'First Floor Parapet Wall',
    22: 'OverHeaad water Tank',
    23: 'Top Floor Water Proofing',
    24: "Ramp 3 'High From Road Level & lying of 3' Dia Three Pipes",
    25: 'Septic Tanks',
    26: 'Internal Drainage(for Rain Water) should be connected to road/drain',
    27: 'Gate and Boundary Wall and Plot Measuring',
    28: 'In Case of Corner Plot Boundary wall should be Chamfered	',
    29: '*** Finishing (Material/ Colour)',
    30: 'Gas/ Electric Meters',
    31: 'Site Clearance'
};
export default listData;
